package entity;

public class SqlEntity {

	public String getSqlEntity(String sqlId) {
		StringBuffer result = new StringBuffer("");
		if ("Q_WL_ZONGZ_BTS".equals(sqlId)) {
			// 查询综资2G基站数据
			result.append("select distinct * from ( SELECT ").append(" b.BTS_NUM,b.DESCRIPTION,z.CITY_NAME,b.COVERAGE,b.VENDOR,b.TYPE_FLAG,b.STATUS, ").append(" b.HOSTADDRESS,b.STATIONCATALOG,b.NAMEININMS, '' as ").append(" maintenanceDept,'' as ").append(" maintenanceSubDept,b.INSERT_TIME,b.BSC_ID,a.LONGITUDE as ").append(" ANT_LONGITUDE,a.LATITUDE as ANT_LATITUDE ,'BTS' as NET_TYPE, ").append(" b.ROOM_ID, b.VIP_TYPE, b.MAINTENANCE_COMPANY, ").append(" b.START_TIME,b.SHALIASNAME,b.ID,b.BTS_NAME,b.PROVINCE_ID,b.CITY_ID,b.COUNTY_ID,b.ROOM_ID ").append(" ,c.LAC,c.CI,g.SD_NAME FROM META_ZONGZ_BTS b left join META_ZONGZ_CITY z on ").append(" b.COUNTY_ID=z.ID left join META_ZONGZ_CELL c on ").append(" b.BTS_NUM=c.BTS_NUM left join META_ZONGZ_ANTENNA a on ")
					.append(" a.CELL_NAME=c.DISCRIPTION  left join META_SD_ZONE g on  ").append(" substring(z.CITY_NAME,1,2)=g.ZONE_NAME where {b.STATUS in (#999status#)} {and ").append(" z.CITY_NAME in (#999cityName#)} {and b.DESCRIPTION like #name#} ").append(" {and b.COVERAGE =#coverage#}{and b.BTS_NUM=#netId#} {and ").append(" b.STATIONCATALOG in (#999stationCategory#)} {and b.HOSTADDRESS ").append(" like #hostAddress# } { and (b.HOSTADDRESS like ").append(" #remoteuinitAddress# or (b.REMOTEUINITADDRESS != '' and ").append(" b.REMOTEUINITADDRESS like #remoteuinitAddress#))} { and ").append(" (b.HOSTADDRESS like #hostAddressNong# or b.HOSTADDRESS like ").append(" #hostAddressHao# )} { and ((b.HOSTADDRESS like ").append(" #remoteuinitAddressNong# or b.HOSTADDRESS like ")
					.append(" #remoteuinitAddressHao# ) or (b.REMOTEUINITADDRESS != '' and ").append(" (b.REMOTEUINITADDRESS like #remoteuinitAddressNong# or ").append(" b.REMOTEUINITADDRESS like #remoteuinitAddressHao#)))} {and ").append(" a.LONGITUDE>=#minLongitude# and a.LONGITUDE<=#maxLongitude# ").append(" and a.LATITUDE>=#minLatitude# and a.LATITUDE<=#maxLatitude#} ").append(" ) m");
		} else if ("Q_WL_ZONGZ_NODEB".equals(sqlId)) {
			// 查询综资3G基站数据
			result.append("select distinct * from ( SELECT ").append(" b.NODEB_NUM,b.DESCRIPTION,z.CITY_NAME,b.COVERAGE,b.VENDOR,b.FRE_BAND,b.STATUS, ").append(" b.HOSTADDRESS,b.STATIONCATALOG, ").append(" b.INSERT_TIME,b.RNC_ID,a.LONGITUDE as ANT_LONGITUDE,a.LATITUDE ").append(" as ANT_LATITUDE ,'NODEB' as NET_TYPE, b.ROOM_ID, b.VIP_TYPE, ").append(" b.MAINTENANCE_COMPANY, ").append(" b.START_TIME,b.SHALIASNAME,b.ID,b.NODEB_NAME,b.PROVINCE_ID,b.CITY_ID,b.COUNTY_ID,b.ROOM_ID,c.LAC,c.CI,g.SD_NAME ").append(" FROM META_ZONGZ_NODEB b left join META_ZONGZ_CITY z on ").append(" b.COUNTY_ID=z.ID left join META_ZONGZ_UTRANCELL c on ").append(" b.NODEB_NUM=c.BTS_NUM left join META_ZONGZ_ANTENNA a on ").append(" a.CELL_NAME=c.DISCRIPTION left join META_SD_ZONE g on  ")
					.append(" substring(z.CITY_NAME,1,2)=g.ZONE_NAME where {b.STATUS in (#999status#)} {and ").append(" b.DESCRIPTION like #name#} {and b.COVERAGE =#coverage#} {and ").append(" z.CITY_NAME in (#999cityName#)} {and b.NODEB_NUM=#netId#} {and ").append(" b.STATIONCATALOG in (#999stationCategory#)} {and b.HOSTADDRESS ").append(" like #hostAddress# } { and (b.HOSTADDRESS like ").append(" #remoteuinitAddress# or (b.REMOTEUINITADDRESS != '' and ").append(" b.REMOTEUINITADDRESS like #remoteuinitAddress#))} { and ").append(" (b.HOSTADDRESS like #hostAddressNong# or b.HOSTADDRESS like ").append(" #hostAddressHao# )} { and ((b.HOSTADDRESS like ").append(" #remoteuinitAddressNong# or b.HOSTADDRESS like ").append(" #remoteuinitAddressHao# ) or (b.REMOTEUINITADDRESS != '' and ")
					.append(" (b.REMOTEUINITADDRESS like #remoteuinitAddressNong# or ").append(" b.REMOTEUINITADDRESS like #remoteuinitAddressHao#)))} {and ").append(" a.LONGITUDE>=#minLongitude# and a.LONGITUDE<=#maxLongitude# ").append(" and a.LATITUDE>=#minLatitude# and a.LATITUDE<=#maxLatitude#} ").append(" ) m");
		} else if ("Q_WL_ZONGZ_ENODEB".equals(sqlId)) {
			// 查询综资4G基站数据
			result.append("select distinct * from ( SELECT ").append(" b.ENODEBID,b.DESCRIPTION,z.CITY_NAME,b.COVERAGE,b.VENDOR,b.USER_FRE_BAND,b.STATUS, ").append(" b.HOSTADDRESS,b.stationCatalog, a.LONGITUDE as ").append(" ANT_LONGITUDE,a.LATITUDE as ANT_LATITUDE ,'ENODEB' as NET_TYPE, ").append(" b.ROOM_ID, b.VIP_TYPE, b.MAINTENANCE_COMPANY, ").append(" b.START_TIME,b.SHALIASNAME,b.ID,b.ENODEB_NAME,b.PROVINCE_ID,b.CITY_ID,b.COUNTY_ID,b.ROOM_ID,b.OMC_NAME, ").append(" c.ECGI,'' as INSERT_TIME ,g.SD_NAME FROM META_ZONGZ_ENODEB b left join ").append(" META_ZONGZ_CITY z on b.COUNTY_ID=z.ID left join ").append(" META_ZONGZ_EUTRANCELL c on b.ENODEBID=c.BTS_NUM left join ").append(" META_ZONGZ_ANTENNA a on a.CELL_NAME=c.DISCRIPTION left join META_SD_ZONE g on ")
					.append(" substring(z.CITY_NAME,1,2)=g.ZONE_NAME where ").append(" {b.STATUS in (#999status#)} {and b.DESCRIPTION like #name#} {and ").append(" b.COVERAGE =#coverage#} {and z.CITY_NAME in (#999cityName#)} ").append(" {and b.ENODEBID=#netId#} {and b.STATIONCATALOG in ").append(" (#999stationCategory#)} {and b.HOSTADDRESS like #hostAddress# } ").append(" { and (b.HOSTADDRESS like #remoteuinitAddress# or ").append(" (b.REMOTEUINITADDRESS != '' and b.REMOTEUINITADDRESS like ").append(" #remoteuinitAddress#))} { and (b.HOSTADDRESS like ").append(" #hostAddressNong# or b.HOSTADDRESS like #hostAddressHao# )} { ").append(" and ((b.HOSTADDRESS like #remoteuinitAddressNong# or ").append(" b.HOSTADDRESS like #remoteuinitAddressHao# ) or ")
					.append(" (b.REMOTEUINITADDRESS != '' and (b.REMOTEUINITADDRESS like ").append(" #remoteuinitAddressNong# or b.REMOTEUINITADDRESS like ").append(" #remoteuinitAddressHao#)))} {and a.LONGITUDE>=#minLongitude# and ").append(" a.LONGITUDE<=#maxLongitude# and a.LATITUDE>=#minLatitude# and ").append(" a.LATITUDE<=#maxLatitude#} ) m");
		} else if ("Q_WL_ZONGZ_CELL".equals(sqlId)) {
			// 查询综资2G小区数据
			result.append("SELECT c.DISCRIPTION,z.CITY_NAME,c.CI,c.LAC,c.COVERAGE ").append(" ,a.LONGITUDE as ANT_LONGITUDE,a.LATITUDE as ANT_LATITUDE, ").append(" c.COVER_UNIVERSIT,c.TYPE_FLAG,c.STATUS,c.STARTE_TIME,c.STATIONCATALOG,c.BTS_NUM,b.DESCRIPTION ").append(" as BTS_NAME,c.DEVICENORMALADDRESS,'' as NAMEININMS,'' as ").append(" maintenanceDept,'' as ").append(" maintenanceSubDept,c.INSERT_TIME,c.ID,a.ANTENNA_HEIGHT,a.DIRECTION_ANGLE ").append(" as ").append(" ANT_DIRECTION_ANGLE,c.PROVINCE_ID,c.CITY_ID,c.COUNTY_ID,c.ROOM_ID,a.TYPE,a.TOTAL_ANGLE, ").append(" a.ELEC_DOWN_ANGLE,a.MACHINE_DOWN_ANGLE,c.BTS_ID,a.ANTENNA_NAME ").append(" FROM dbo.META_ZONGZ_CELL c left join META_ZONGZ_CITY z on ").append(" c.COUNTY_ID=z.ID left join META_ZONGZ_ANTENNA a on ")
					.append(" a.CELL_NAME=c.DISCRIPTION left join META_ZONGZ_BTS b on ").append(" c.BTS_NUM=b.BTS_NUM where {c.STATUS in (#999status#)} {and ").append(" z.CITY_NAME in (#999cityName#)} {and c.DISCRIPTION like #name#} ").append(" {and c.COVERAGE =#coverage#} {and c.STATIONCATALOG in ").append(" (#999stationCategory#)} {and a.LONGITUDE>=#minLongitude# and ").append(" a.LONGITUDE<=#maxLongitude# and a.LATITUDE>=#minLatitude# and ").append(" a.LATITUDE<=#maxLatitude#}");
		} else if ("Q_WL_ZONGZ_UTRANCELL".equals(sqlId)) {
			// 查询综资3G小区数据
			result.append("SELECT c.DISCRIPTION,z.CITY_NAME,c.CI,c.LAC,c.COVERAGE ").append(" ,a.LONGITUDE as ANT_LONGITUDE,a.LATITUDE as ANT_LATITUDE, ").append(" c.COVER_UNIVERSIT,c.USE_FRE_BAND,c.STATUS,c.STARTE_TIME,c.STATIONCATALOG,c.BTS_NUM,b.DESCRIPTION ").append(" as BTS_NAME,c.DEVICENORMALADDRESS, '' as NAMEININMS, '' as ").append(" maintenanceDept, '' as maintenanceSubDept, ").append(" c.INSERT_TIME,c.ID,a.ANTENNA_HEIGHT,a.DIRECTION_ANGLE as ").append(" ANT_DIRECTION_ANGLE,c.PROVINCE_ID,c.CITY_ID,c.COUNTY_ID,c.ROOM_ID,a.TYPE,a.TOTAL_ANGLE, ").append(" a.ELEC_DOWN_ANGLE,a.MACHINE_DOWN_ANGLE,c.NODEB_ID,a.ANTENNA_NAME ").append(" FROM META_ZONGZ_UTRANCELL c left join META_ZONGZ_CITY z on ").append(" c.COUNTY_ID=z.ID left join META_ZONGZ_ANTENNA a on ")
					.append(" a.CELL_NAME=c.DISCRIPTION left join META_ZONGZ_NODEB b on ").append(" c.BTS_NUM=b.NODEB_NUM where {c.STATUS in (#999status#)} {and ").append(" z.CITY_NAME in (#999cityName#)} {and c.DISCRIPTION like #name#} ").append(" {and c.COVERAGE =#coverage#} {and c.STATIONCATALOG in ").append(" (#999stationCategory#)} {and a.LONGITUDE>=#minLongitude# and ").append(" a.LONGITUDE<=#maxLongitude# and a.LATITUDE>=#minLatitude# and ").append(" a.LATITUDE<=#maxLatitude#}");
		} else if ("Q_WL_ZONGZ_EUTRANCELL".equals(sqlId)) {
			// 查询综资4G小区数据
			result.append("SELECT c.DISCRIPTION,z.CITY_NAME,c.CI,c.LAC,c.COVERAGE ").append(" ,a.LONGITUDE as ANT_LONGITUDE,a.LATITUDE as ANT_LATITUDE, ").append(" c.COVER_UNIVERSIT,c.USER_FRE_BAND_ID,c.STATUS,c.START_TIME,c.STATIONCALALOG,c.BTS_NUM,b.DESCRIPTION ").append(" as BTS_NAME,c.DEVICENORMALADDRESS,'' as NAMEININMS,'' as ").append(" maintenanceDept,'' as maintenanceSubDept,'' as ").append(" INSERT_TIME,c.ID,a.ANTENNA_HEIGHT,a.DIRECTION_ANGLE as ").append(" ANT_DIRECTION_ANGLE,c.PROVINCE_ID,c.CITY_ID,c.COUNTY_ID,c.ROOM_ID,a.TYPE,a.TOTAL_ANGLE, ").append(" a.ELEC_DOWN_ANGLE,a.MACHINE_DOWN_ANGLE,c.ENODEB_ID,a.ANTENNA_NAME ").append(" FROM META_ZONGZ_EUTRANCELL c left join META_ZONGZ_CITY z on ").append(" c.COUNTY_ID=z.ID left join META_ZONGZ_ANTENNA a on ")
					.append(" a.CELL_NAME=c.DISCRIPTION left join META_ZONGZ_ENODEB b on ").append(" c.BTS_NUM=b.ENODEBID where {c.STATUS in (#999status#)} {and ").append(" z.CITY_NAME in (#999cityName#)} {and c.DISCRIPTION like #name#} ").append(" {and c.COVERAGE =#coverage#} {and c.STATIONCALALOG in ").append(" (#999stationCategory#)} {and a.LONGITUDE>=#minLongitude# and ").append(" a.LONGITUDE<=#maxLongitude# and a.LATITUDE>=#minLatitude# and ").append(" a.LATITUDE<=#maxLatitude#}");
		}
		return result.toString();
	}
}
